### ISSUE TITLE
AvroConvert.Deserialize throws "Unable to deserialize [map] of schema [Map] to the target type"

### ISSUE THREAD

**Issue by ivanrvf** [AdrianStrugala/AvroConvert#98]
**What is the bug?**
Please provide a bug description
I am trying to get data from avro file generated by Azure EventHub. I want to be able to convert the data into EventData. This works when I use Avro2json function of AvroConvert perfectly but it tedious process to convert json string to JsonDocument and work with it. I tried to use AvroConvert.Deserialize function and it gives me following exception: - 

Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SolTechnology.Avro.AvroConvert.Deserialize(Byte[] avroBytes, Type targetType)
   at RandomPrograms.ConvertAvroToJson.Main(String[] args) in C:\Users\<Scraped-Data>\source\repos\RandomPrograms\RandomPrograms\ConvertAvroToJson.cs:line 31
Unable to deserialize [EventData] of schema [Record] to the target type [RandomPrograms.EventData]. Inner exception:
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.ResolveArray(TypeSchema writerSchema, TypeSchema readerSchema, IReader d, Type type, Int64 itemsCount)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve[T](IReader reader, Int64 itemsCount)
   at SolTechnology.Avro.Features.Deserialize.Decoder.Read[T](Reader reader, Header header, AbstractCodec codec, Resolver resolver)
   at SolTechnology.Avro.Features.Deserialize.Decoder.Decode[T](Stream stream, TypeSchema readSchema)
   at SolTechnology.Avro.AvroConvert.Deserialize[T](Byte[] avroBytes)
System.Collections.ListDictionaryInternal
End of SolTechnology.Avro.Infrastructure.Exceptions.AvroTypeMismatchException: Unable to deserialize [EventData] of schema [Record] to the target type [RandomPrograms.EventData]. Inner exception: ---> SolTechnology.Avro.Infrastructure.Exceptions.AvroTypeMismatchException: Unable to deserialize [map] of schema [Map] to the target type [System.Collections.ObjectModel.ReadOnlyDictionary`2[System.String,System.Object]]. Inner exception: ---> System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.ResolveMap(MapSchema writerSchema, TypeSchema readerSchema, IReader d, Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
   --- End of inner exception stack trace ---
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.<>c__DisplayClass19_1.<ResolveRecord>b__1()
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.ResolveRecord(RecordSchema writerSchema, RecordSchema readerSchema, IReader dec, Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
   --- End of inner exception stack trace ---
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.ResolveArray(TypeSchema writerSchema, TypeSchema readerSchema, IReader d, Type type, Int64 itemsCount)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve[T](IReader reader, Int64 itemsCount)
   at SolTechnology.Avro.Features.Deserialize.Decoder.Read[T](Reader reader, Header header, AbstractCodec codec, Resolver resolver)
   at SolTechnology.Avro.Features.Deserialize.Decoder.Decode[T](Stream stream, TypeSchema readSchema)
   at SolTechnology.Avro.AvroConvert.Deserialize[T](Byte[] avroBytes)
Unable to deserialize [map] of schema [Map] to the target type [System.Collections.ObjectModel.ReadOnlyDictionary`2[System.String,System.Object]]. Inner exception:
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.<>c__DisplayClass19_1.<ResolveRecord>b__1()
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.ResolveRecord(RecordSchema writerSchema, RecordSchema readerSchema, IReader dec, Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
System.Collections.ListDictionaryInternal
End of SolTechnology.Avro.Infrastructure.Exceptions.AvroTypeMismatchException: Unable to deserialize [map] of schema [Map] to the target type [System.Collections.ObjectModel.ReadOnlyDictionary`2[System.String,System.Object]]. Inner exception: ---> System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.ResolveMap(MapSchema writerSchema, TypeSchema readerSchema, IReader d, Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
   --- End of inner exception stack trace ---
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.<>c__DisplayClass19_1.<ResolveRecord>b__1()
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.ResolveRecord(RecordSchema writerSchema, RecordSchema readerSchema, IReader dec, Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.ResolveMap(MapSchema writerSchema, TypeSchema readerSchema, IReader d, Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
System.Collections.ListDictionaryInternal
End of System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.ResolveMap(MapSchema writerSchema, TypeSchema readerSchema, IReader d, Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)

**How to reproduce?**
Please provide steps for reproducing the bug
Line of code that produces the issue: -
var avroBytes = File.ReadAllBytes(ConfigurationManager.AppSettings["AvroFileLocation"].ToString()); // Read avro file. 
var test = (List</EventData/>)AvroConvert.Deserialize(avroBytes, typeof(List</EventData/>));

*What is the Avro schema?*
```
Schema: {"type":"record","name":"EventData","namespace":"Microsoft.ServiceBus.Messaging","fields":[{"name":"SequenceNumber","type":"long"},{"name":"Offset","type":"string"},{"name":"EnqueuedTimeUtc","type":"string"},{"name":"SystemProperties","type":{"type":"map","values":["long","double","string","bytes"]}},{"name":"Properties","type":{"type":"map","values":["long","double","string","bytes","null"]}},{"name":"Body","type":["null","bytes"]}]}
```
Model class: - 
Expected Model: public class EventData
{
	public long SequenceNumber { get; set; }
	public string Offset { get; set; }
	public string EnqueuedTimeUtc { get; set; }
	public Dictionary<string,[
  "long",
  "double",
  "string",
  "byte[]"
]> SystemProperties { get; set; }
	public Dictionary<string,[
  "long",
  "double",
  "string",
  "byte[]",
  "null"
]> Properties { get; set; }
	public byte[]? Body { get; set; }
}

Model class in my code: - 
[DataContract(Namespace = "Microsoft.ServiceBus.Messaging")]
    public class EventData
    {
        public long SequenceNumber { get; set; }
        public string Offset { get; set; }
        public string EnqueuedTimeUtc { get; set; }

        //[NullableSchema]
        //[DefaultValue("['long','double','string','bytes'")]
        public ReadOnlyDictionary<string, object> SystemProperties { get; set; }

        //[NullableSchema]
        //[DefaultValue("['long','double','string','bytes'")]
        public Dictionary<string, object> Properties { get; set; }
        
        [DefaultValue("test")]
        public string Body { get; set; }
    }

*What is the Avro data? Fill up the section or provide a sample file*
```
[tmp34.avro.txt](https://github.com/AdrianStrugala/AvroConvert/files/10855960/tmp34.avro.txt)

it is sample avro file generated from Azure Eventhub capture feature -> https://learn.microsoft.com/en-us/azure/event-hubs/explore-captured-avro-files. 

Please change the file extension by removing .txt.
```

**What is the expected behavior?**
My expectation is I should be able to get list of EventData and I should be able to parse each data easily as below. - 
var test = (List</EventData/>)AvroConvert.Deserialize(avroBytes, typeof(List</EventData/>));
foreach (EventData item in test)
                {
                System.Diagnostics.Debug.WriteLine(item.Body);
                }

**Comment by AdrianStrugala** [comment]
Hello,

Thank you for reporting the bug. I can confirm that the problem is with the reading union of  `['long','double','string','bytes'")]` types. It is a complex case, so I expect it to take a few days to fix.

Regards,
Adrian

**Comment by ivanrvf** [comment]
Thank you for letting me know.
Changed the title and updated below line in the main post: -
from: var test = (List<EventData>)AvroConvert.Deserialize(avroBytes, typeof(List<EventData>));
to: var test = (List</EventData/>)AvroConvert.Deserialize(avroBytes, typeof(List</EventData/>));

**Comment by AdrianStrugala** [comment]
Hello @ivanrvf,

The problem should be resolved starting from **v.3.3.4 of AvroConvert**.
The case of yours including map of union types is now supported - [reference](https://github.com/AdrianStrugala/AvroConvert/blob/master/tests/AvroConvertTests/ComplexDeserialization/DeserializeAzureEventHub.cs)

Additionally, your invocation could be simplified to: `var test = AvroConvert.Deserialize<List<EventData>>(avroBytes)`
Please let me know if it resolves your problem.

Regards,
Adrian

**Comment by ivanrvf** [comment]
@AdrianStrugala this works now. Thank you!

I am not sure if this is supposed to work but the deserializeHeadless is giving following exception: - 

Code:
var result = AvroConvert.DeserializeHeadless</List</EventData/>/>(avroBytes);

Exception:

Exception thrown: 'SolTechnology.Avro.Infrastructure.Exceptions.AvroTypeMismatchException' in SolTechnology.Avro.dll
Unable to deserialize [array] of schema [Array] to the target type [System.Collections.Generic.List`1[RandomPrograms.EventData]]. Inner exception:
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve[T](IReader reader, Int64 itemsCount)
   at SolTechnology.Avro.AvroConvert.DeserializeHeadless[T](Byte[] avroBytes, TypeSchema writeSchema, TypeSchema readSchema, Int32 numberOfRows)
   at SolTechnology.Avro.AvroConvert.DeserializeHeadless[T](Byte[] avroBytes)
   at RandomPrograms.ConvertAvroToJson.Main(String[] args) in C:\Users\<Scraped-Data>\source\repos\RandomPrograms\RandomPrograms\ConvertAvroToJson.cs:line 35
Unable to deserialize [EventData] of schema [Record] to the target type [RandomPrograms.EventData]. Inner exception:
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.ResolveArray(TypeSchema writerSchema, TypeSchema readerSchema, IReader d, Type type, Int64 itemsCount)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
System.Collections.ListDictionaryInternal
End of SolTechnology.Avro.Infrastructure.Exceptions.AvroTypeMismatchException: Unable to deserialize [EventData] of schema [Record] to the target type [RandomPrograms.EventData]. Inner exception: ---> SolTechnology.Avro.Infrastructure.Exceptions.AvroTypeMismatchException: Unable to deserialize [string] of schema [String] to the target type [System.String]. Inner exception: ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at SolTechnology.Avro.AvroObjectServices.Read.Reader.ReadString()
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.ResolveString(Type type, IReader reader)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
   --- End of inner exception stack trace ---
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.<>c__DisplayClass20_1.<ResolveRecord>b__1()
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.ResolveRecord(RecordSchema writerSchema, RecordSchema readerSchema, IReader dec, Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
   --- End of inner exception stack trace ---
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.ResolveArray(TypeSchema writerSchema, TypeSchema readerSchema, IReader d, Type type, Int64 itemsCount)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
Unable to deserialize [string] of schema [String] to the target type [System.String]. Inner exception:
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.<>c__DisplayClass20_1.<ResolveRecord>b__1()
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.ResolveRecord(RecordSchema writerSchema, RecordSchema readerSchema, IReader dec, Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
System.Collections.ListDictionaryInternal
End of SolTechnology.Avro.Infrastructure.Exceptions.AvroTypeMismatchException: Unable to deserialize [string] of schema [String] to the target type [System.String]. Inner exception: ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at SolTechnology.Avro.AvroObjectServices.Read.Reader.ReadString()
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.ResolveString(Type type, IReader reader)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
   --- End of inner exception stack trace ---
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.<>c__DisplayClass20_1.<ResolveRecord>b__1()
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.ResolveRecord(RecordSchema writerSchema, RecordSchema readerSchema, IReader dec, Type type)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
Arithmetic operation resulted in an overflow.
   at SolTechnology.Avro.AvroObjectServices.Read.Reader.ReadString()
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.ResolveString(Type type, IReader reader)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
System.Collections.ListDictionaryInternal
End of System.OverflowException: Arithmetic operation resulted in an overflow.
   at SolTechnology.Avro.AvroObjectServices.Read.Reader.ReadString()
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.ResolveString(Type type, IReader reader)
   at SolTechnology.Avro.AvroObjectServices.Read.Resolver.Resolve(TypeSchema writerSchema, TypeSchema readerSchema, IReader reader, Type type)
The program '[15288] RandomPrograms.exe: Program Trace' has exited with code 0 (0x0).
The program '[15288] RandomPrograms.exe' has exited with code 0 (0x0).

**Comment by AdrianStrugala** [comment]
The DeserializeHeadless would not work, as your avro file contain header
